version: "2"
services:

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ~/Desktop/blogpy_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - my_blogpy


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_blogpy
    restart: always
    ports:
      - "8000:8000"
    networks:
      - my_blogpy
    volumes:
      - .:/usr/src/app
    depends_on:
      - database


networks:
  my_blogpy:
    external: true