# Generated by Django 3.1.2 on 2020-10-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpy_articles', '0006_auto_20201028_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
