# Generated by Django 3.1.2 on 2020-10-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpy_articles', '0007_auto_20201028_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله'),
        ),
    ]
