# Generated by Django 3.1.2 on 2020-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpy_articles', '0009_auto_20201029_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='special',
            field=models.BooleanField(default=False, verbose_name='پست ویژه'),
        ),
    ]
