# Generated by Django 3.1.2 on 2020-10-29 16:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpy_articles', '0010_article_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='user_profile/', verbose_name='تصویر نویسنده')),
                ('description', ckeditor.fields.RichTextField(verbose_name='معرفی نویسنده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پروفایل نویسنده',
                'verbose_name_plural': 'پروفایل های نویسندگان',
            },
        ),
    ]
