# Generated by Django 3.1.2 on 2020-10-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpy_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ی ما'},
        ),
    ]
